server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: http://localhost:8084/
        predicates:
        - Path=/employees/**
      - id: userModule
        uri: http://localhost:8085/
        predicates:
        - Path=/users/**